//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.02 at 12:29:07 PM WAT 
//


package com.gaf.reminderserver.notificationModels;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserDefinedData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDefinedData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="udfName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="udfValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="udfDataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="udfDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDefinedData", propOrder = {
    "udfName",
    "udfValue",
    "udfDataType",
    "udfDescription"
})
public class UserDefinedData {

    @XmlElement(required = true)
    protected String udfName;
    @XmlElement(required = true)
    protected String udfValue;
    @XmlElement(required = true)
    protected String udfDataType;
    @XmlElement(required = true)
    protected String udfDescription;

    /**
     * Gets the value of the udfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUdfName() {
        return udfName;
    }

    /**
     * Sets the value of the udfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUdfName(String value) {
        this.udfName = value;
    }

    /**
     * Gets the value of the udfValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUdfValue() {
        return udfValue;
    }

    /**
     * Sets the value of the udfValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUdfValue(String value) {
        this.udfValue = value;
    }

    /**
     * Gets the value of the udfDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUdfDataType() {
        return udfDataType;
    }

    /**
     * Sets the value of the udfDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUdfDataType(String value) {
        this.udfDataType = value;
    }

    /**
     * Gets the value of the udfDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUdfDescription() {
        return udfDescription;
    }

    /**
     * Sets the value of the udfDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUdfDescription(String value) {
        this.udfDescription = value;
    }

}
